import Head from "next/head";
import styles from "@/styles/Home.module.css";
import WorkoutList from "@/components/WorkoutList/WorkoutList";
import Link from "next/link";

export default function Workouts() {
    return (
        <>
            <Head>
                <title>Workout Planner</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Link href={'/'}>Back</Link>
                <h1>Workouts</h1>
                <WorkoutList />
            </main>
            <footer className={styles.footer}>

            </footer>
        </>
    );
}
